### ISSUE TITLE
from_file in process.Audio dimension issue

### ISSUE THREAD

**Issue by Rahul-Brito** [sensein/b2aiprep#4]
https://github.com/sensein/b2aiprep/blob/ac73e7b1cf043415d2bec1a2338755c1199b9ce6/src/b2aiprep/process.py#L34

When I run from_file on data/test_audio.wav I get the error:

`IndexError: too many indices for tensor of dimension 1`

Since the signal that gets loaded only has one dimension. Is this a data issue or is the code handling the situation incorrectly?

**Comment by satra** [comment]
i thought i checked two types of files. but this is where tensor shapes on different channel data can be different. if you simply load it what does the shape look like?

i would change that to: 

```python
if len(signal.shape) > 1 and ...
    ...
else:
    signal = signal[:, None]
```

**Comment by Rahul-Brito** [comment]
That audio looks like this: 
<img width="185" alt="image" src="https://github.com/sensein/b2aiprep/assets/78616918/c95ab592-a3a6-4ce3-93c0-25a7ffdbe217">


It was a mono 44khz audio I recorded in audacity.

I can make the change
