### ISSUE TITLE
load_and_pivot_questionnaire: "cannot reindex on an axis with duplicate labels"

### ISSUE THREAD

**Issue by ArtKrutsko** [sensein/b2aiprep#69]
![image](https://github.com/sensein/b2aiprep/assets/124406508/e65910c6-82ab-4310-aa8d-6ef409f47419)

![image](https://github.com/sensein/b2aiprep/assets/124406508/266e3ee5-d750-40ca-8a87-00e983c88329)

**Comment by ibevers** [comment]
We figured out a fix in office hours
