### ISSUE TITLE
Discrepancy in the number of audio files in conversion

### ISSUE THREAD

**Issue by ibevers** [sensein/b2aiprep#82]
<img width="892" alt="Screenshot 2024-10-07 at 5 12 11 PM" src="https://github.com/user-attachments/assets/c62e0967-d229-4fc1-93c9-becfa1ade6e7">

**Comment by ibevers** [comment]
@alistairewj do you have this too?

**Comment by alistairewj** [comment]
No - my files are consistent between the source and the output in BIDS format - but I also have 12523 audio files for corpus 3 which is far more than you have.

**Comment by ibevers** [comment]
@alistairewj My audio file path was pointing to Corpus 2.
